version: 2.1

harbor_auth: &harbor_auth
  auth:
    username: $HARBOR_USERNAME
    password: $HARBOR_PASSWORD

executors:
  test_runner:
    docker:
      - image: harbor-public.test.musubu.co.in/dockerio/mysql:8.0.33
        <<: *harbor_auth
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_TCP_PORT: 15306
          MYSQL_DATABASE: sunstrika
      - image: harbor-public.test.musubu.co.in/dockerio/redis:7.2.3-alpine
        <<: *harbor_auth
    environment:
      DB_HOST: "localhost"
      DB_USER: "root"
      DB_PORT: 15306
      DB_PASS: ""
      DB_NAME: sunstrika
      REDIS_PORT: 6379

jobs:
  build:
    docker:
      - image: harbor-public.test.musubu.co.in/dockerio/golang:1.17.13
        <<: *harbor_auth
    resource_class: small
    working_directory: /tmp/touyahoge
    steps:
      - checkout
      - run:
          name: Build binary
          command: |
            mkdir build/
            cd src
            go build -o ../build/goapp
      - persist_to_workspace:
          root: /tmp/touyahoge
          paths:
            - "build/goapp"

  test:
    resource_class: small
    executor:
      name: test_runner
    steps:
      - attach_workspace:
          at: /tmp/touyahoge
      - run:
          name: Executing Go app
          command: |
            cd /tmp/touyahoge
            ./build/goapp

workflows:
  build_n_test:
    jobs:
      - build:
          context: harbor-public-shared-creds
      - test:
          context: harbor-public-shared-creds
          requires:
            - build
