version: 2.1

harbor_auth: &harbor_auth
  auth:
    username: $HARBOR_USERNAME
    password: $HARBOR_PASSWORD

executors:
  test_runner:
    docker:
      - image: harbor-public.test.musubu.co.in/dockerio/cimg/mysql:8.0
        name: touya_db
        <<: *harbor_auth
      - image: harbor-public.test.musubu.co.in/dockerio/cimg/redis:5.0.14
        name: redis
        <<: *harbor_auth

jobs:
  # build:
  #   docker:
  #     - image: harbor-public.test.musubu.co.in/dockerio/golang:1.17.13
  #       <<: *harbor_auth
  #   resource_class: small
  #   working_directory: /tmp/touyahoge
  #   steps:
  #     - checkout
  #     # - run:
  #     #     name: Build binary
  #     #     command: |
  #     #       mkdir build/
  #     #       cd src
  #     #       go build -o ../build/goapp
  #     # - persist_to_workspace:
  #     #     root: /tmp/touyahoge
  #     #     paths:
  #     #       - "build/goapp"

  test:
    resource_class: small
    executor:
      name: test_runner
    steps:
      - attach_workspace:
          at: /tmp/touyahoge
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://touya_db:3306 -timeout 1m
      - run: curl -v telnet://touya_db:3306
      - run:
          name: Executing Go app
          command: |
            cd /tmp/touyahoge
            ./build/goapp

workflows:
  build_n_test:
    jobs:
      # - build:
      #     context: harbor-public-shared-creds
      - test:
          context: harbor-public-shared-creds
          # requires:
          #   - build
